config/routes.rb
Rails.application.routes.draw do


   resources :piramides
   resources :contacts, only: [:new, :create]
   resources :sanfonadas
   resources :contencoes
   resources :galpoes
   resources :personalizadas
   resources :sob_medidas

   root 'welcome#index'



end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
  	{
	  	:subject => "Contact Form",
	  	:to => "lwstendas@hotmail.com",
	  	:from => %("#{name}" <#{email}>)
	  }
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	# def create
	# 	@contact = Contact.new(params[:contact])
  #   @contact.request = request
  #   if @contact.deliver
  #     flash.now[:error] = nil
  #   else
  #     flash.now[:error] = 'Cannot send message.'
  #     render :new
  #   end
	# end
end

app/controllers/contencoes_controller.rb
class ContencoesController < ApplicationController
end

app/controllers/galpoes_controller.rb
class GalpoesController < ApplicationController

  
end

app/controllers/personalizadas_controller.rb
class PersonalizadasController < ApplicationController
end

app/controllers/piramides_controller.rb
class PiramidesController < ApplicationController
end

app/controllers/sanfonadas_controller.rb
class SanfonadasController < ApplicationController
end

app/controllers/sob_medidas_controller.rb
class SobMedidasController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/contencoes_helper.rb
module ContencoesHelper
end

app/helpers/galpoes_helper.rb
module GalpoesHelper
end

app/helpers/personalizadas_helper.rb
module PersonalizadasHelper
end

app/helpers/piramides_helper.rb
module PiramidesHelper
end

app/helpers/sanfonadas_helper.rb
module SanfonadasHelper
end

app/helpers/sob_medidas_helper.rb
module SobMedidasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
  <div class="container-contacts">
    <div class="container">
    <div class="section" style="margin-top:75px;">


      <div class="row" id="contacts">
        <div class="col s12 m12">

            <div class="col s12 center">

            <h2 class="title-harvy">Obrigado pela sua mensagem!</h2>
            <p>
              retornaremos em breve!
            </p>


        </div>

        </div>


      </div>

    </div>
  </div>
  </div>

app/views/contacts/new.html.erb
  <div class="container-contacts">
    <div class="container">
    <div class="section" style="margin-top:100px;">


      <div class="row" id="contacts">
        <div class="col s12 m12">

            <div class="col s12 center">

            <h4 class="title-harvy">Contato</h4>
            <hr>
            <%= form_for @contact do |f| %>
          		<%= f.label :Nome%>
          		<%= f.text_field :name, required:true%>

          		<br>

          		<%= f.label :Email%><br>
          		<%= f.email_field :email, required:true%>

          		<br>

          		<%= f.label :Mensagem%><br>
          		<%= f.text_area :message, as: :text%><br>

          		<div class="hidden">
          			<%= f.label :nickname%><br>
          			<%= f.text_area :nickname, hint: 'leave this field blank'%><br>
          		</div>
          		<%= f.submit 'Enviar', class: 'waves-effect waves-light btn brown lighten-1'%><br>
          	<% end %>

        </div>

        </div>


      </div>

    </div>
  </div>
  </div>

app/views/contencoes/index.html.erb
<div class="container-galpao" id="products">
   <div class="container down-container " >
    <div class="section" >





    <div class="row " >
      <div id="gallery" class="content">
					<div id="controls" class="controls"></div>
					<div class="slideshow-container">
						<div id="loading" class="loader"></div>
						<div id="slideshow" class="slideshow"></div>
					</div>
					<div id="caption" class="caption-container"></div>
				</div>
				<div id="thumbs" class="navigation">
					<ul class="thumbs noscript">
						<li>
			              <a class="thumb" name="leaf" href="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/barricadas_de_protecao/barricada_1.jpg?raw=true" title="Title # 1">
			                <img src="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/barricadas_de_protecao/barricada_1.jpg?raw=true" alt="Title #1"  class="small_img" />
			              </a>
			              <div class="caption">
			                <div class="image-title">Barricadas de contenção</div>
			              </div>
						</li>
						<li>
			              <a class="thumb" name="leaf" href="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/barricadas_de_protecao/barricada_2.jpg?raw=true" title="Title # 2">
			                <img src="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/barricadas_de_protecao/barricada_2.jpg?raw=true" alt="Title #2"  class="small_img" />
			              </a>
			              <div class="caption">
			                <div class="image-title">Barricadas de contenção</div>
			              </div>
						</li>
						<li>
			              <a class="thumb" name="leaf" href="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/barricadas_de_protecao/barricada_3.jpg?raw=true" title="Title # 3">
			                <img src="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/barricadas_de_protecao/barricada_3.jpg?raw=true" alt="Title #3"  class="small_img" />
			              </a>
			              <div class="caption">
			                <div class="image-title">Barricadas de contenção</div>
			              </div>
						</li>
						<li>
			              <a class="thumb" name="leaf" href="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/barricadas_de_protecao/barricada_4.jpg?raw=true" title="Title # 4">
			                <img src="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/barricadas_de_protecao/barricada_4.jpg?raw=true" alt="Title #4"  class="small_img" />
			              </a>
			              <div class="caption">
			                <div class="image-title">Barricadas de contenção</div>
			              </div>
						</li>
						
						<li>
			              <a class="thumb" name="leaf" href="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/barricadas_de_protecao/barricada_6.jpg?raw=true" title="Title # 6">
			                <img src="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/barricadas_de_protecao/barricada_6.jpg?raw=true" alt="Title #6"  class="small_img" />
			              </a>
			              <div class="caption">
			                <div class="image-title">Barricadas de contenção</div>
			              </div>
						</li>
						<li>
			              <a class="thumb" name="leaf" href="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/barricadas_de_protecao/barricada_7.jpg?raw=true" title="Title # 7">
			                <img src="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/barricadas_de_protecao/barricada_7.jpg?raw=true" alt="Title #7"  class="small_img" />
			              </a>
			              <div class="caption">
			                <div class="image-title">Barricadas de contenção</div>
			              </div>
						</li>
						<li>
			              <a class="thumb" name="leaf" href="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/barricadas_de_protecao/barricada_8.jpg?raw=true" title="Title # 8">
			                <img src="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/barricadas_de_protecao/barricada_8.jpg?raw=true" alt="Title #8"  class="small_img" />
			              </a>
			              <div class="caption">
			                <div class="image-title">Barricadas de contenção</div>
			              </div>
						</li>
							
					</ul>
				</div>
				<div style="clear: both;"></div>
			</div>
		</div>

		<script type="text/javascript">
			jQuery(document).ready(function($) {
				// We only want these styles applied when javascript is enabled
				$('div.navigation').css({'width' : '300px', 'float' : 'left'});
				$('div.content').css('display', 'block');

				// Initially set opacity on thumbs and add
				// additional styling for hover effect on thumbs
				var onMouseOutOpacity = 0.67;
				$('#thumbs ul.thumbs li').opacityrollover({
					mouseOutOpacity:   onMouseOutOpacity,
					mouseOverOpacity:  1.0,
					fadeSpeed:         'fast',
					exemptionSelector: '.selected'
				});

				// Initialize Advanced Galleriffic Gallery
				var gallery = $('#thumbs').galleriffic({
					delay:                     2500,
					numThumbs:                 15,
					preloadAhead:              10,
					enableTopPager:            true,
					enableBottomPager:         true,
					maxPagesToShow:            7,
					imageContainerSel:         '#slideshow',
					controlsContainerSel:      '#controls',
					captionContainerSel:       '#caption',
					loadingContainerSel:       '#loading',
					renderSSControls:          true,
					renderNavControls:         true,
					playLinkText:              '',
					pauseLinkText:             '',
					prevLinkText:              '',
					nextLinkText:              '',
					nextPageLinkText:          'Proximo &rsaquo;',
					prevPageLinkText:          '&lsaquo; Anterior',
					enableHistory:             false,
					autoStart:                 false,
					syncTransitions:           true,
					defaultTransitionDuration: 900,
					onSlideChange:             function(prevIndex, nextIndex) {
						// 'this' refers to the gallery, which is an extension of $('#thumbs')
						this.find('ul.thumbs').children()
							.eq(prevIndex).fadeTo('fast', onMouseOutOpacity).end()
							.eq(nextIndex).fadeTo('fast', 1.0);
					},
					onPageTransitionOut:       function(callback) {
						this.fadeTo('fast', 0.0, callback);
					},
					onPageTransitionIn:        function() {
						this.fadeTo('fast', 1.0);
					}
				});
			});
		</script>
    </div>



  </div>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html >
<head>
  <title>LWS Tendas</title>

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="white" role="navigation" >
    <div class="nav-wrapper">
      <a id="logo-container" href="/" class="page-scroll brand-logo"><%= image_tag "logo.png" %></a>
      <ul class="right hide-on-med-and-down">
        <li class="page-scroll"><a href="/#how">Quem somos</a></li>
        <li class="page-scroll"><a href="/#products">Produtos</a></li>
        <li class="page-scroll"><a href="/#cases">Clientes</a></li>
        <li><%= link_to 'Contato', new_contact_path%></li>
         <li><a href="tel:+556232783779" class="fone">(62) 3278-3779</a></li>
      </ul>


      <ul id="nav-mobile" class="side-nav">
        <li class="page-scroll"><a href="/#how">Quem somos</a></li>
        <li class="page-scroll"><a href="/#products">Produtos</a></li>
        <li class="page-scroll"><a href="/#cases">Clientes</a></li>
        <li><%= link_to 'Contato', new_contact_path%></li>

      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>


<%= yield %>

  <footer class="page-footer brown lighten-1">
    <div class="container">
      <a href="" class="topo"><i class="fa fa-arrow-up fa-2x"></i></a>
      <div class="row">
        <div class="col l3 s12">
          <h5 class="white-text"><u class="this-about">
            LWS Tendas
          </u></h5>
          <ul>
           <li class="page-scroll"><a class="white-text" href="#how">Quem somos</a></li>
            <li class="page-scroll"><a class="white-text" href="#products">Produtos</a></li>
            <li class="page-scroll"><a class="white-text" href="#cases">Cases</a></li>
            <li><%= link_to 'Contatos', new_contact_path, :class => "white-text"%> </li>
          </ul>


        </div>


        <div class="col l3 s12">
          <ul>
            <li><p class="white-text">Telefones:<br>(62) 3278-3779<br>
            (62) 99665660<br>
            (62) 94795640<br>
            (62) 92079243<br>
            (62) 84084201 </p></li>
          </ul>
        </div>
        <div class="col l6 s12">
          <div id="map"></div>
                <script>
            function initMap() {
              var mapDiv = document.getElementById('map');
              var map = new google.maps.Map(mapDiv, {
                center: {lat: -16.7655761, lng: -49.2431809},
                zoom: 17
              });

              var marker = new google.maps.Marker({
                position: {lat: -16.7655761, lng: -49.2431809},
                map: map,
                title: 'LWS Tendas'
              });

            }

          </script>
          <script src="https://maps.googleapis.com/maps/api/js?callback=initMap"
              async defer></script>
        </div>

      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      <span class="right">Create by <a href="mailto:igor.p.r.vieira@gmail.com" target="_blank" class="blue-text text-lighten-3" >Igor Vieira</a>& <a href="mailto:gabrielgyn97@hotmail.com" target="_blank" class=" blue-text text-lighten-3">Gabriel Gonçalves</a></span>
      <span class="left">AV. JK/DO PEDRO II Qd.3 Lt.23 - Jardim Transbrasiliano - Aparecida de Goiânia</span>
      </div>
    </div>
  </footer>

</body>
</html>

app/views/sob_medidas/index.html.erb
<div class="container-galpao" id="products">
   <div class="container down-container " >
    <div class="section" >





    <div class="row " >
      <div id="gallery" class="content">
					<div id="controls" class="controls"></div>
					<div class="slideshow-container">
						<div id="loading" class="loader"></div>
						<div id="slideshow" class="slideshow"></div>
					</div>
					<div id="caption" class="caption-container"></div>
				</div>
				<div id="thumbs" class="navigation">
					<ul class="thumbs noscript">
						<li>
			              <a class="thumb" name="leaf" href="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/tenda_sob_medida/tenda_1.jpg?raw=true" title="Title # 1">
			                <img src="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/tenda_sob_medida/tenda_1.jpg?raw=true" alt="Title #1"  class="small_img" />
			              </a>
			              <div class="caption">
			                <div class="image-title">Tendas Sob Medida</div>
			              </div>
						</li>
						<li>
			              <a class="thumb" name="leaf" href="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/tenda_sob_medida/tenda_2.jpg?raw=true" title="Title # 2">
			                <img src="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/tenda_sob_medida/tenda_2.jpg?raw=true" alt="Title #2"  class="small_img" />
			              </a>
			              <div class="caption">
			                <div class="image-title">Tendas Sob Medida</div>
			              </div>
						</li>
						<li>
			              <a class="thumb" name="leaf" href="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/tenda_sob_medida/tenda_3.jpg?raw=true" title="Title # 3">
			                <img src="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/tenda_sob_medida/tenda_3.jpg?raw=true" alt="Title #3"  class="small_img" />
			              </a>
			              <div class="caption">
			                <div class="image-title">Tendas Sob Medida</div>
			              </div>
						</li>
						<li>
			              <a class="thumb" name="leaf" href="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/tenda_sob_medida/tenda_4.jpg?raw=true" title="Title # 4">
			                <img src="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/tenda_sob_medida/tenda_4.jpg?raw=true" alt="Title #4"  class="small_img" />
			              </a>
			              <div class="caption">
			                <div class="image-title">Tendas Sob Medida</div>
			              </div>
						</li>
						<li>
			              <a class="thumb" name="leaf" href="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/tenda_sob_medida/tenda_5.jpg?raw=true" title="Title # 5">
			                <img src="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/tenda_sob_medida/tenda_5.jpg?raw=true" alt="Title #5"  class="small_img" />
			              </a>
			              <div class="caption">
			                <div class="image-title">Tendas Sob Medida</div>
			              </div>
						</li>
						<li>
			              <a class="thumb" name="leaf" href="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/tenda_sob_medida/tenda_6.jpg?raw=true" title="Title # 6">
			                <img src="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/tenda_sob_medida/tenda_6.jpg?raw=true" alt="Title #6"  class="small_img" />
			              </a>
			              <div class="caption">
			                <div class="image-title">Tendas Sob Medida</div>
			              </div>
						</li>
						
							
					</ul>
				</div>
				<div style="clear: both;"></div>
			</div>
		</div>

		<script type="text/javascript">
			jQuery(document).ready(function($) {
				// We only want these styles applied when javascript is enabled
				$('div.navigation').css({'width' : '300px', 'float' : 'left'});
				$('div.content').css('display', 'block');

				// Initially set opacity on thumbs and add
				// additional styling for hover effect on thumbs
				var onMouseOutOpacity = 0.67;
				$('#thumbs ul.thumbs li').opacityrollover({
					mouseOutOpacity:   onMouseOutOpacity,
					mouseOverOpacity:  1.0,
					fadeSpeed:         'fast',
					exemptionSelector: '.selected'
				});

				// Initialize Advanced Galleriffic Gallery
				var gallery = $('#thumbs').galleriffic({
					delay:                     2500,
					numThumbs:                 15,
					preloadAhead:              10,
					enableTopPager:            true,
					enableBottomPager:         true,
					maxPagesToShow:            7,
					imageContainerSel:         '#slideshow',
					controlsContainerSel:      '#controls',
					captionContainerSel:       '#caption',
					loadingContainerSel:       '#loading',
					renderSSControls:          true,
					renderNavControls:         true,
					playLinkText:              '',
					pauseLinkText:             '',
					prevLinkText:              '',
					nextLinkText:              '',
					nextPageLinkText:          'Proximo &rsaquo;',
					prevPageLinkText:          '&lsaquo; Anterior',
					enableHistory:             false,
					autoStart:                 false,
					syncTransitions:           true,
					defaultTransitionDuration: 900,
					onSlideChange:             function(prevIndex, nextIndex) {
						// 'this' refers to the gallery, which is an extension of $('#thumbs')
						this.find('ul.thumbs').children()
							.eq(prevIndex).fadeTo('fast', onMouseOutOpacity).end()
							.eq(nextIndex).fadeTo('fast', 1.0);
					},
					onPageTransitionOut:       function(callback) {
						this.fadeTo('fast', 0.0, callback);
					},
					onPageTransitionIn:        function() {
						this.fadeTo('fast', 1.0);
					}
				});
			});
		</script>
    </div>



  </div>
 </div>
</div>

app/views/welcome/index.html.erb
<div id="home">
      <div id="index-banner" class="parallax-container down_container">
      <div class="section no-pad-bot">
        <div class="container">

          <h1 class="banner_lws header center deep-orange-text text-lighten-2">LWS Tendas</h1>
          <div class="row center">
            <div class="logo_lws header col s12 light  deep-orange darken-4"><h1>
              Tudo em tendas e Galvanização
            </h1></div>
          </div>

          <br><br>

        </div>
      </div>
      <div class="parallax"><%= image_tag "background2.jpg" %></div>
    </div>
  </div>



  <div class="container-about">
    <div class="container">
    <div class="section" id="how">


      <div class="row" >

            <div class="col s12 m6">

            <h4 class="title-harvy center" >Quem somos</h4>

            <hr>
            <p class="left-align light">
                  A LWS TENDAS vem se consolidando no mercado com o objetivo de entregar máxima qualidade, resistência e beleza aos seus clientes. Visando sempre proporcionar soluções praticas e econômicas. Com a missão de produzir tendas diferenciadas temos como meta principal proporcionar uma qualidade superior, e sempre levando em conta detalhes que ao final da confecção fazem a total diferença.
            </p>
        </div>
        <div class="col s12 m6">
          <div class="slider ">
            <ul class="slides">
              <li>
                <img src="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/piramidais/15x15_piramidal/15x15_3.jpg?raw=true"> <!-- random image -->
                <div class="caption center-align">
                  <h3 class="deep-orange black-text">Tendas para o que você quer...</h3>
                  <h5 class=" deep-orange lighten-2 light silver-text text-lighten-3">como você precisa</h5>
                </div>
              </li>
              <li>
                <img src="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/tenda_galpao/galpao_4.jpg?raw=true"> <!-- random image -->
                <div class="caption left-align">
                  <h3 class="deep-orange black-text">Trazendo diferencial...</h3>
                  <h5 class=" deep-orange lighten-2 light silver-text text-lighten-3"> e concretizando o seu negócio.</h5>
                </div>
              </li>
              <li>
                <img src="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/barricadas_de_protecao/barricada_6.jpg?raw=true"> <!-- random image -->
                <div class="caption right-align">
                  <h3 class="deep-orange black-text">Usando o melhor... </h3>
                  <h5 class=" deep-orange lighten-2 light silver-text text-lighten-3">para lhe atender.</h5>
                </div>
              </li>
              <li>
                <img src="https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/tenda_sob_medida/tenda_1.jpg?raw=true"> <!-- random image -->
                <div class="caption center-align">
                  <h3 class="deep-orange black-text">Buscando ser o que você precisa...</h3>
                  <h5 class=" deep-orange lighten-2 light silver-text text-lighten-3"> para o seu negócio!</h5>
                </div>
              </li>
            </ul>
          </div>
        </div>


      </div>

    </div>
  </div>
  </div>

<div class="container-product" id="products">
   <div class="container " >
    <div class="section" >





    <div class="row" >
       <h4  class="center white-text title-harvy">Produtos</h4>
          <hr>

          <div class="col s12 m4">
          <div class="card ">
            <div class="card-image">
              <%= image_tag "https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/piramidais/15x15_piramidal/15x15_2.jpg?raw=true" %>
              <span class="card-title">Tenda Piramidal</span>
            </div>
            <div class="card-action">
              <a href="#"><%= link_to 'Veja mais', piramides_path%></a>
            </div>
          </div>
        </div>
         <div class="col s12 m4">

        </div>
         <div class="col s12 m4">
          <div class="card ">
            <div class="card-image">
              <%= image_tag "https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/Sanfonadas/3x3/3x3_5.jpg?raw=true" %>
              <span class="card-title">Tenda Sanfonadas</span>
            </div>
            <div class="card-action">
              <a href="#"><%= link_to 'Veja mais', sanfonadas_path%></a>
            </div>
          </div>
        </div>
         <div class="col s12 m4">
          <div class="card ">
            <div class="card-image">
              <%= image_tag "https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/Sanfonadas/3x3/3x3_2.jpg?raw=true" %>
              <span class="card-title">Tenda Personalizada</span>
            </div>
            <div class="card-action">
              <a href="#"><%= link_to 'Veja mais', personalizadas_path%></a>
            </div>
          </div>
        </div>
         <div class="col s12 m4">
          <div class="card ">
            <div class="card-image">
              <%= image_tag "https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/tenda_sob_medida/tenda_1.jpg?raw=true" %>
              <span class="card-title">Tenda Sob Medida</span>
            </div>
            <div class="card-action">
              <a href="#"><%= link_to 'Veja mais', sob_medidas_path%></a>
            </div>
          </div>
        </div>
        <div class="col s12 m4">
          <div class="card ">
            <div class="card-image">
              <%= image_tag "https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/tenda_galpao/galpao_4.jpg?raw=true" %>
              <span class="card-title">Tenda Galpão</span>
            </div>
            <div class="card-action">
              <a href="#"><%= link_to 'Veja mais', galpoes_path%></a>
            </div>
          </div>
        </div>
        <div class="col s12 m4">
          <div class="card ">
            <div class="card-image">
              <%= image_tag "https://github.com/IgorVieira/lws-tendas-rubyonrails/blob/master/app/assets/images/barricadas_de_protecao/barricada_6.jpg?raw=true" %>
              <span class="card-title">Barricadas de Contenção</span>
            </div>
            <div class="card-action">
              <a href="#"><%= link_to 'Veja mais', contencoes_path%></a>
            </div>
          </div>
        </div>
    </div>



  </div>
 </div>
</div>

    <div class="container-cases" id="cases">
      <div class="container">
      <div class="section" >


        <div class="row" >

              <div class="col s12 m12">

              <h4  class="center white-text title-harvy">Alguns de Nossos Clientes</h4>

              <hr>

              <%= image_tag "agrocanassa.jpg"  %>
              <%= image_tag "allegratche.jpg" %>
              <%= image_tag "conopus.jpg" %>
              <%= image_tag "pintosrunners.jpg" %>

          </div>


        </div>

      </div>
    </div>
    </div>